In [3]:
import numpy as np
print(np.empty((2,2),dtype=int))


[[-1767571280       32760]
 [-1767566752       32760]]


In [4]:
import numpy as np
array=np.zeros(10,dtype=int)
array[4]=1
print(*array)

0 0 0 0 1 0 0 0 0 0


In [5]:
import numpy as np
li=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(li)
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
b=np.random.rand(3,4)
b

array([[0.84170479, 0.18847191, 0.02791996, 0.2868018 ],
       [0.97691594, 0.47399631, 0.56646882, 0.79296068],
       [0.57056694, 0.85680254, 0.79745503, 0.02180211]])

In [9]:
a = np.array([0, 1, 2, 3])
a.shape



(4,)

In [10]:
np.random.rand()

0.1672803175116564

In [50]:
np.random.randint(50)

2

In [51]:
np.random.randint(10,size=(4,4))

array([[7, 0, 2, 1],
       [5, 6, 1, 0],
       [7, 4, 9, 8],
       [7, 3, 9, 8]])

In [57]:
import numpy as np
b=np.linspace(0,5,9,dtype=float)
for i in b:
    print(i)
print(b[1]-b[0],b[2]-b[1])

0.0
0.625
1.25
1.875
2.5
3.125
3.75
4.375
5.0
0.625 0.625


In [58]:
import numpy as np
x= np.linspace(0,5,10)[1:9]
c=np.around(x,decimals=2)
for i in c:
    print(i)

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


In [70]:
import numpy as np
a=np.array([1,2,0,0,4,0])

b=np.where(a != 0 )[0]
print(*b)
for i in b:
    print(i,end=' ')

0 1 4
0 1 4 

In [76]:
## Print the required output in given format
import numpy as np
a=np.array([1,3,5,7,9,11,13,15,17,19])
b=np.where(a%3==0)[0]
print(*b)

1 4 7


In [81]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2!=0]=-1

print(*a)


-1 2 -1 4 -1 6 -1 8 -1 10


In [17]:
import numpy as np
a=np.array([11,2,13,4,15,6,27,8,19])
a[np.where(a==a.max())]=0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


In [22]:
import numpy as np
a=np.array([1,2,-3,-4,-5,-6,-7,-8,9,10])
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [40]:
import numpy as np
a=np.arange(1,11,1)
index=np.where((a>=3) & (a<=8))
for i in index:
    a[i]=np.negative(a[i])
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


In [4]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
height1=np.where(height>155)
print(height1)
for i in range(len(height1[0])):
    print(age[height1[0][i]],height[height1][i])


(array([ 0,  2,  3,  5, 10, 11, 13, 14, 16, 17, 18], dtype=int64),)
15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


In [13]:
import numpy as np
a=np.array( [[21, 20, 19, 18, 17],[16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]])
print(a)


[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


AxisError: axis -1 is out of bounds for array of dimension 0

In [17]:
import numpy  as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=list(filename)
country=[]
killed=[]
for row in filedata:
    if row["Country"]=='United States':
        killed.append(row['Killed'])
kill=np.array(killed)
kill[kill=='']='0.0'
kill=np.array(kill,dtype=float)
print(np.sum(kill,dtype=int))

3771


In [18]:
import numpy  as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=list(filename)
country=[]
killed=[]
for row in filedata:
    country.append(row["Country"])
    killed.append(row['Killed'])
kill=np.array(killed)
kill[kill=='']='0.0'
ans=kill[country=='United States']
kill=np.array(ans,dtype=float)
print(np.sum(kill,dtype=int))

0


In [6]:
import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=list(filename)
day=[]
for row in filedata:
        day.append(row['Day'])
day=np.array(day,dtype=int)
day=day[(day>=10) & (day<=20)]
count=0

for i in range(len(day)):
    count+=1
print(count)

66330


In [9]:
import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=list(filename)
day=[]
for row in filedata:
    if row['Year']=='2010' and row['Month']=='1':
        day.append(row['Day'])
day=np.array(day,dtype=int) 
day=day[(day>=1)&(day<=31)]
count=0
for i in range(len(day)):
    count+=1
print(count)

271


In [5]:
import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filedata=csv.DictReader(file,skipinitialspace=True)
    wounded=[]
    city=[]
    group=[]
    killed=[]
    for row in filedata:
        if row['Year']=='1999' and row["State"]=="Jammu and Kashmir":
            a=row['Month']
            if a=='5' or a=='6' or a=='7':
                group.append(row['Group'])
                city.append(row['City'])
                killed.append(row['Killed'])
                wounded.append(row['Wounded'])
kill=np.array(killed)
kill[kill=='']='0.0'
wound=np.array(wounded)
wound[wound=='']='0.0'
kill=np.array(kill,dtype=float)
wound=np.array(wound,dtype=float)
casualities=kill+wound
casual=np.array(casualities,dtype=int)
city=np.array(city)
group=np.array(group)
maxcasual=np.argmax(casual)
cas=np.max(casual)
city=city[maxcasual]
group=group[maxcasual]
print(cas,city,group)



22 Kargil District Separatists


In [11]:
import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=filename                 # Don't make list it will increase time complexity 
    kill=[]
    wound=[]
    for row in filedata:
        a=row['State']
        if a=='Jharkhand' or a=='Odisha' or a=='Andhra Pradesh' or a=='Chhattisgarh':
            kill.append(row['Killed'])
            wound.append(row['Wounded'])
kill=np.array(kill)
wound=np.array(wound)
kill[kill=='']='0.0'
wound[wound=='']='0.0'
kill=np.array(kill,dtype=float)
wound=np.array(wound,dtype=float)
casual=kill+wound
count=np.sum(casual,dtype=int)
print(count)

5628


In [12]:
import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filedata=csv.DictReader(file,skipinitialspace=True)
    wounded=[]
    city=[]
    killed=[]
    dict={}
    for row in filedata:
        if row['Country']=='India' and row['City']!='Unknown':
            city.append(row['City'])
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
kill=np.array(killed)
city=np.array(city)
wound=np.array(wounded)
kill[kill=='']='0.0'
wound[wound=='']='0.0'
kill=np.array(kill,dtype=float)
wound=np.array(wound,dtype=float)
casual=kill+wound
dict={}
for i in range(len(city)):
    if city[i] in dict:
        dict[city[i]]+=casual[i]
    else:
        dict[city[i]]=casual[i]
a=dict.sort()[::-1]
print(a)

AttributeError: 'dict' object has no attribute 'sort'

In [10]:
with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    killed=[]
    wounded=[]
    city=[]
    for row in file_data:
        if 'India' in row['Country'] and 'Unknown' not in row['City']:
            city.append(row['City'])
            wounded.append(row['Wounded'])
            killed.append(row['Killed'])
    np_wounded=np.array(wounded)
    np_killed=np.array(killed)
    np_city=np.array(city)
    
    np_killed[np_killed=='']='0.0'
    np_wounded[np_wounded=='']='0.0'
    np_killed=np.array(np_killed, dtype='float')
    np_wounded=np.array(np_wounded, dtype='float')
    np_casuality=np.array(np_wounded+np_killed, dtype='int')
    
    
    citydic={}
    for i in range(len(np_city)):
        if np_city[i] in citydic:
            citydic[np_city[i]]+=np_casuality[i]
        else:
            citydic[np_city[i]]=np_casuality[i]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    
    count=0
    city=''
    for i in citydic:
        if citydic[i]>count:
            count=citydic[i]
            city=i
    print(city, count)
    del citydic[city]
    

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


In [14]:
import numpy as np
import csv

with open('terrorismData.csv', encoding='utf8') as file_obj:
    file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])

15 6500


In [43]:
## Print the required output in given format
import csv
import numpy as np
fileObj=open("terrorismData.csv",encoding='utf-8')
fileData= csv.DictReader(fileObj)
cas=[]
for i in fileData:
    a=i['State']
    if a=='Jharkhand' or a=='Odisha' or a=='Andhra Pradesh' or a=='Chhattisgarh':
        cas.append([i['Wounded'],i['Killed']])
#for i in fileData:
#    if i['State']=='Jharkhand' or i['State']=='Odisha' or i['State']=='Andhra Pradesh' or i['State']=='Chattisgarh':
#        cas.append([i['Wounded'],i['Killed']])
npcas=np.array(cas)
npcas[npcas==""]=0
npcas=np.array(npcas,dtype=float)
npcas=np.sum(npcas,axis=1)
print(int(np.sum(npcas)))

    

5628


In [39]:
import csv
import numpy as np
fileObj=open("terrorismData.csv",encoding='utf-8')
fileData= csv.DictReader(fileObj)
cas=[]
for i in fileData:
    if i['State']=='Jharkhand' or i['State']=='Odisha' or i['State']=='Andhra Pradesh' or i['State']=='Chattisgarh':
        cas.append([i['Wounded'],i['Killed']])
npcas=np.array(cas)
npcas[npcas==""]=0
npcas=np.array(npcas,dtype=float)
npcas=np.sum(npcas,axis=1)
print(int(np.sum(npcas)))


3110


In [4]:
import numpy  as np
import csv
with open('terrorismData.csv',encoding="utf8") as file:
    filename=csv.DictReader(file,skipinitialspace=True)
    filedata=list(filename)
country=[]
killed=[]
for row in filedata:
    if row["Country"]=='United States':
        killed.append(row['Killed'])
kill=np.array(killed)
kill[kill=='']='0.0'
kill=np.array(kill,dtype=float)
count=0
for i in kill:
    count=count+i;
    
print(int(count))

3771


In [3]:
import csv
import numpy as np
with open('terrorismData.csv',encoding='UTF-8') as file_obj:
    file_data= csv.DictReader(file_obj,skipinitialspace=True)
    file_list=list(file_data)
    
killed=[]
country=[]
for row in file_list:
    killed.append(row['Killed'])
    country.append(row['Country'])
np_killed=np.array(killed)
np_country=np.array(country)
np_killed[np_killed==' ']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_killed=np.array(np_killed,dtype=int)
bool_arr=[np_country=='United States']
ans=np_killed[bool_arr]
for i in ans:
    print(i)

ValueError: could not convert string to float: ''

In [14]:
## Open and read data file as specified in the question
## Print the required output in given format
import pandas as pd
import numpy as np
td=pd.read_csv('terrorismData.csv', encoding='utf8')
df_terrorism=td.copy()
year=len(set(df_terrorism['Year']))
df_terrorism=df_terrorism[df_terrorism['Country']=='India']
df_terrorism['Casualty']=df_terrorism['Killed']+df_terrorism['Wounded']
Jammu_state=df_terrorism[df_terrorism['State']=='Jammu and Kashmir']
red_state=df_terrorism[(df_terrorism['State']=='Jharkhand')|(df_terrorism['State']=='Odisha')
                       |(df_terrorism['State']=='Andhra Pradesh')|(df_terrorism['State']=='Chhattisgarh')]
red_casualty=int(np.sum(red_state['Casualty']))
print(red_casualty)
Jammu_casualty=int(np.sum(Jammu_state['Casualty']))
print(red_casualty//year,Jammu_casualty//year)


5448
115 261


In [10]:
## Print the required output in given format
import pandas as pd
import numpy as np
a = pd.read_csv("terrorismData.csv")
b = a.copy()
x = b[(b.State == "Jharkhand")|(b.State == "Odisha")|(b.State == "Andhra Pradesh")|(b.State == "Chhattisgarh")]

c1 = x.Killed.sum() + x.Wounded.sum()
print(c1)
ans1 = c1/(b.Year.value_counts().index.size)
y = b[b.State == "Jammu and Kashmir"]
c2 = np.sum(y['Killed']) + np.sum(y['Wounded'])
ans2 = c2/(b.Year.value_counts().index.size)
print(str(int(ans1))," ",str(int(ans2)))

5628.0
119   269
